### ISSUE TITLE
what is the license?

### ISSUE THREAD

**Issue by snowch** [vikrantlabde/iso8583-Java#1]
What is the license?  I couldn't see it in the source code.

**Comment by vikrantlabde** [comment]
GNU. will add that,

On Mon, Apr 15, 2013 at 11:32 AM, snowch notifications@github.com wrote:

> What is the license? I couldn't see it in the source code.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/vikrantlabde/iso8583-Java/issues/1
> .

## 

Vikrant Labde
Co-founder, CTO
Cuelogic Technologies PVT LTD
Mobile: +91 9960688497
Direct line:  020 41254049
http://www.cuelogic.co.in

**Comment by vikrantlabde** [comment]
Added the GNU licence information
